npmScopes:
awesome.me:
  npmAlwaysAuth: true
  npmRegistryServer: "https://npm.fontawesome.com/"
  npmAuthToken: "FAPS-TPDT-EGBJ-NBQD-3943"
fortawesome:
  npmAlwaysAuth: true
  npmRegistryServer: "https://npm.fontawesome.com/"
  npmAuthToken: "FAPS-TPDT-EGBJ-NBQD-3943"
